AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Hit counter Lambda + API + Dynamo

Globals:
  Function:
    Timeout: 3
  Api:
    ThrottlingBurstLimit: 10
    ThrottlingRateLimit: 5

Resources:
  HitCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hit-counter/ # or whatever folder your Lambda code lives in
      Handler: app.handler # or app.lambdaHandler depending on your file
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HitCounterApi:
          Type: Api
          Properties:
            Path: /hitCounter
            Method: get
            ThrottlingBurstLimit: 5
            ThrottlingRateLimit: 2
      Environment:
        Variables:
          TABLE_NAME: HitCounter
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !GetAtt HitCounterTable.Arn

  HitCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HitCounter
      AttributeDefinitions:
        - AttributeName: path
          AttributeType: S
      KeySchema:
        - AttributeName: path
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  HitCounterApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hitCounter/"
  HitCounterFunctionArn:
    Description: "Lambda ARN"
    Value: !GetAtt HitCounterFunction.Arn
  HitCounterFunctionRole:
    Description: "Lambda IAM Role"
    Value: !GetAtt HitCounterFunctionRole.Arn
